<?php

namespace Container6Jnxp6R;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAuthorControllernewService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.43tWQYB.App\Controller\Admin\AuthorController::new()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.43tWQYB'] ?? $container->load('get_ServiceLocator_43tWQYBService'));

        if (isset($container->privates['.service_locator.43tWQYB.App\\Controller\\Admin\\AuthorController::new()'])) {
            return $container->privates['.service_locator.43tWQYB.App\\Controller\\Admin\\AuthorController::new()'];
        }

        return $container->privates['.service_locator.43tWQYB.App\\Controller\\Admin\\AuthorController::new()'] = $a->withContext('App\\Controller\\Admin\\AuthorController::new()', $container);
    }
}
