<?php

namespace Container6Jnxp6R;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBookControllernewService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.43tWQYB.App\Controller\Admin\BookController::new()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.43tWQYB.App\\Controller\\Admin\\BookController::new()'] = ($container->privates['.service_locator.43tWQYB'] ?? $container->load('get_ServiceLocator_43tWQYBService'))->withContext('App\\Controller\\Admin\\BookController::new()', $container);
    }
}
